Comfy-Org/litegraph.js

css/litegraph.css, src/litegraph.js
Add 20 commits on https://github.com/comfyanonymous/litegraph.js/tree/comfyui to master.
These changes are consider stable as they have served in the ComfyUI main repo for very long time (~3 months)
=> Comfy UI custom changes

package.json
ComfyUI only uses `litegraph.core.js`, importing the full version results unexpected nodes to be available.
=> Only publish litegraph.core.js

package.json
`src/litegraph.js` seems to be the most up-to-date version also used in the main ComfyUI repo. Package that instead of `dist/litegraph.core.js`
=> Distribute src/litegraph.js

README.md, package.json, src/litegraph.d.ts, src/litegraph.js
This PR makes litegraph emits 2 events:
- `litegraph:canvas` - empty-release
- `litegraph:canvas` - empty-double-click
Both event can be observed from outside of litegraph to know when to show a search box. This PR is the preparation to replace litegraph's searchbox with an external searchbox.
=> Emit searchbox triggering canvas events

package.json, src/litegraph.js
Reverts #9 as it breaks node compatibility, which was used in jest testing in ComfyUI_frontend.
=> Revert ESM change

src/litegraph.js
Fix event detail to match typescript schema declaration.
```ts
export type LiteGraphCanvasEvent = CustomEvent<{
subType: string;
originalEvent: Event,
linkReleaseContext?: LinkReleaseContext;
}>;
```
=> Fix event detail

src/litegraph.js
Some widgets (combo, number) render overflowing text currently:
This change truncates the displayed text on the combo widgets, without changing the underlying values:
https://github.com/user-attachments/assets/e66bf60b-f505-4635-9235-d96a982a6d52
=> Truncate overflowing combo widget text

src/litegraph.js
When dragging a link onto a node, it will always replace the first matching input type, unless you drop in the (respectively tiny) input hit box.
This commit fixes that, honouring the intended behaviour (preferFreeSlot is true in internal calls).
This _is_ a breaking change.  But you know, in the good way.
=> Fix empty input not used when connecting links

src/litegraph.js
Before we convert litegraph to module, the cloned was referencing field on the global window object.
=> Fix undefined var 'cloned'

src/litegraph.js
Add ARIA attributes to contextmenu entries to indicate their role, whether they are disabled, whether they have submenus, and whether they are currently expanded or not.
=> Add ARIA attributes to contextmenu

src/litegraph.js
Adds disconnect feature and very minor bug fixes (in separate commits):
- Ctrl + Alt + Click: Disconnect all links from an input or output
- Ctrl + Alt + Click & Drag: Disconnect all links & link to a new node with a single click
- Added LiteGraph setting, on by default
Not sure why skip_action was set to true, here. It prevents disconnect and drag to a new output on the same click, so I've included it in the main commit. Ideally, this should be controlled by a consumer hook, e.g. create "onDisconnectInput".
=> Add node disconnect shortcuts

src/litegraph.js
When an output connects to multiple inputs, and you'd like to move all of those links to another node, you are currently required to drag each new link one by one.
Hold shift to pull all links on an output to a new node, or new output.  Does not disconnect links until they land on a valid target.
It functions with reroute nodes, however it requires that they are dropped onto the new output directly, not just anywhere on the node.  This is expected, really.
It -does not- currently work with the drop to blank space + search for new node.  It will j ust rewire the first.  This can probably be fixed easily enough.
=> Add output multi-link move using shift-click

src/litegraph.d.ts, src/litegraph.js
This PR updates the connection protocol to attach full information about connecting links that expose to the TS frontend.
=> Relands #31 and #32

src/litegraph.js
Fix for:
- comfyanonymous/ComfyUI#4123
The `LGraphGroup` constructor was not using the `DEFAULT_GROUP_FONT` variable.
=> Use group font size from user

src/litegraph.js
With this change, when moving the mouse in circles on empty ComfyUI background, CPU use and calls to drawNode are _significantly_ reduced.
Process use went from ~15-20% down to 7% max.  I have been unable to find a single difference in functionality.
=> Remove extremely inefficient test code

src/litegraph.js
Fixes issue: **de**selecting nodes (`shift + click` or `ctrl + click`) only deselects them visually.  The nodes are still selected.  Example:
- Select 3 nodes
- Deselect two nodes using `ctrl + click`
- Press `Delete`
- Three nodes are deleted
https://github.com/user-attachments/assets/a589ba35-facf-4120-a36f-8b8d8d1334ac
=> Fix deselect delete

src/litegraph.js
`LGraphCanvas.centerOnNode` is used by various extensions. Currently it does not work when browser is zoomed in/out or DPI is not otherwise 1.
Related: 
- comfyanonymous/ComfyUI@4796e61
=> `centerOnNode` use DPI

src/litegraph.js, test/LGraph.test.ts
It seems like if we are not in strict mode, directly write class's prototype is fine. Note: ComfyUI_frontend is no where close to turning on strict mode.
=> Remove unnecessary compatibility layer

src/litegraph.js
JavaScript's sort function sorts nodes in place, which causes a side effect on the graph when calling `serialize`. This PR prevents this side effect.
=> Avoid sort nodes in place

src/litegraph.js
Text truncate in combo widgets was not converting to string before attempting to truncate. If there were combos of numbers or objects and they exceeded the available space, it tried to call `substr` and the entire graph breaks.
After fix it works with all types:
https://github.com/user-attachments/assets/b18b4e47-0a71-4195-92e8-30297c1f903c
=> Fix truncating non-string combo widgets

public/litegraph.d.ts, src/litegraph.js
Related issue: https://github.com/Comfy-Org/ComfyUI_frontend/issues/438
Some users specifically want a certain node order on serialization because the node order defines which node is displayed in front of which when 2 or more nodes overlay with each other. This PR makes sort optional and not sort by default.
=> Make node id serialization optional

src/litegraph.js
Close prompt dialogs by clicking elsewhere on canvas, consistent with how the litegraph context menus work. Currrently you have to click the `OK` button. Escape/Enter also work, but not if the element loses focus. 
Resolves an issue on touch devices in which the `OK` button is rendered offscreen and the dialog is seemingly impossible to dismiss. 
Touch device:
https://github.com/user-attachments/assets/4851a5ea-bf55-4a40-b38f-42eb70781553
Chrome and Firefox:
https://github.com/user-attachments/assets/dc6472e0-774e-4ab2-8972-c24830e8e21c
Related:
- comfyanonymous/ComfyUI#90
=> Close prompt dialog popup on outer canvas click

.github/workflows/test-comfyui-frontend.yml, src/litegraph.js
Occasionally the click event that opened the prompt dialog will be caught by the close click handler and the dialog will be dismissed immediately, making it unusable.
It was not caught by tests because it only seems to happen when the input type is `STRING`.
=> Increase timeout on prompt dialog dismiss

public/litegraph.d.ts
Update `LGraphCanvas` type def to include `zoom_speed` property added in #19
=> Add zoom_speed to LGraphCanvas type def

public/litegraph.d.ts, src/litegraph.js
This PR adds an optional hook `onNodeTitleDblClick` on LGraphNode, and adds all double click hooks to types.
=> Add onNodeTitleDblClick hook

src/litegraph.js, test/LGraphNode.test.ts
Related issue: https://github.com/Comfy-Org/ComfyUI_frontend/issues/710
The issue has been there for a long while, only surfaced by the previous refactor on node construction in #98. The code in question is creating a float array of length 10, while the real intention should be create a float array that initializes to [10, 10].
=> Fix LGraphNode.pos serialization

public/litegraph.d.ts, src/litegraph.js
Other behavior change: double click on group no longer trigger the searchbox.
=> Add litegraph:group-double-click event

public/litegraph.d.ts, src/litegraph.js
The feature is disabled by default. Highlight the bounding box of the current selected group.
https://github.com/user-attachments/assets/661d8607-8e78-40e0-80c5-be5152cd1ad3
=> Add selected group bound highlight

public/litegraph.d.ts, src/litegraph.js
1. Pin icon is moved to the end of title.
2. Pinned not cannot be expanded/collapsed.
=> Add pin icon to end of title

src/litegraph.js
Close: #123 
This bug is because we only scale the foreground canvas, but not the background canvas.
**Before** ![image](https://github.com/user-attachments/assets/06f9afb6-fa1a-4ab4-9da2-dadfe216f75b) **After**![image](https://github.com/user-attachments/assets/bb1d799c-c129-4f9e-8f94-ef2d5f8679f6)
=> Fix blurry links on HiDPI screen

src/litegraph.js
Fixes Comfy-Org/ComfyUI_frontend#751
Using the new frontend on Firefox, the legacy searchbox's input cannot be focused immediately. It is fixed by delaying the focus.
=> Fix legacy searchbox autofocus on Firefox

public/litegraph.d.ts, src/litegraph.js
Expose LGraph's internals private fields with getters so that they becomes observable from outside. Avoid ts-ignore in ComfyUI frontend.
=> Add getters to LGraph private fields

public/litegraph.d.ts, src/litegraph.js
Removed unnecessary getters. Getter fields should be ignored on configure. nodes and groups are all handled separately.
=> Fix configure trying to write to getter field

src/draw.ts, src/litegraph.js
Also extracted slot drawing logic into a separate function.
=> Support hollow circle slot shape

src/litegraph.js
Supports shift+click on the input slot to create a new link from the origin node
=> Allow shift+click on input to create new link from origin node

src/LGraphCanvas.ts
For Mac+Firefox users, allow meta key to be used to drag-select multiple nodes.
Resolves Issues
- https://github.com/Comfy-Org/ComfyUI_frontend/issues/1033
- https://github.com/comfyanonymous/ComfyUI/issues/4984
Also mentioned in:
- https://github.com/Comfy-Org/ComfyUI_frontend/issues/1032
- (Comment) https://github.com/comfyanonymous/ComfyUI/issues/1016#issuecomment-1656755686
Tested with playwright:
=> Fix drag-select on Mac

public/litegraph.d.ts, src/LGraphCanvas.ts
Provides a mechanism for creating links to widgets, for widget->input support by dragging instead of Right Click->Convert to Input
By default, this doesn't do anything, `getWidgetLinkType` needs to be implemented externally.
Enables this:
https://github.com/user-attachments/assets/360013b2-d350-4fb0-bbce-cb860178d9ed
(Sorry poor quality)
=> Support allowing links to widgets

src/LGraphCanvas.ts
Allow Meta+Click to add node to current selection on Mac, mirroring behavior of Ctrl+Click on other OS.
Playwright test case for future reference:
```typescript
test('Can select multiple nodes with Meta+Click (mac)', async ({
comfyPage
}) => {
const clipNodes = await comfyPage.getNodeRefsByType('CLIPTextEncode')
for (const node of clipNodes) {
await node.click('title', { modifiers: ['Meta'] })
}
const selectedNodeCount = await comfyPage.getSelectedGraphNodesCount()
expect(selectedNodeCount).toBe(clipNodes.length)
})
```
=> Fix adding node to selection with Ctrl+Click on Mac

src/LGraphCanvas.ts
Don't draw node badges when zoomed out enough.
=> Don't draw badges when zoomed out

test/LGraph.test.ts, test/LGraphNode.test.ts, vite.config.mts
Saves a little over 150K on the `.umd.js` output file.  Only whitespace / comments are altered.  Names, map, etc are not impacted.  Easily reformats using e.g. prettier.
Does not work for .es.js output - limitation of vite.  Workaround for .es.js involves adding `terser` & a plugin.
=> ES2022 Output & whitespace-only minification

src/LGraphGroup.ts
Mercifully minor PR.  Changes:
- Moves `pos`/`size` getter/setter to class definitions (from dynamic assign in ctor)
- Makes `move()` nodes param optional with original behaviour as default
=> Typescript LGraphGroup

src/LGraph.ts, src/LGraphCanvas.ts, src/litegraph.ts, src/types/events.ts, src/utils/arrange.ts
Based on #220
- Changes the way alt + drag node works under the hood (now same as copy & paste) - fixes minor inconsistencies with downstream customisation
- Changes type checks to `typeof` / `instanceof` / `isArray`
- Removes unused (broken) code
Refactors:
- Standardises event emit calls
- TS types
=> Canvas refactors - standardising

src/LGraphCanvas.ts, src/LGraphGroup.ts, src/LiteGraphGlobal.ts
Adds basic multi-group selection & drag to move.
- Selection combines with nodes, e.g. select any node, then shift + click + drag an unrelated group to move both
- Selecting groups using a drag rectangle requires the group be wholly contained inside it.
https://github.com/user-attachments/assets/e6230a94-411e-4fba-90cb-6c694200adaa
Note: Some of this PR I've already rewritten, but it happens here on my timeline, and is pretty solid.
=> Add multi-group select & drag

src/LGraphCanvas.ts, src/LGraphNode.ts, src/interfaces.ts, src/litegraph.ts
- Backwards compatible
- Moves slot find logic out from `connectByType` functions to new find functions, so links don't need to be backed up, created, deleted, and restored just to get a slot index
- Extend node before-connect callback: can now determine if connection is to a specific input, or just trying to connect any valid slot on the node
- Refactored input/output duplication to generics
=> Add / improve Node interfaces: Find slots & before connect callback

src/LGraphCanvas.ts
Links keep their default curves when dragging multiple outputs.  Behaviour unchanged for "vertical" nodes.
Old behaviour:
New behaviour:
=> Multi-link drag keeps links bundled properly

src/LGraphCanvas.ts, src/litegraph.ts
- POCO that can be proxied without side-effects.
- LGraphCanvasState interface added to package exports
=> Move canvas state to plain object

src/LGraphNode.ts
#226 introduces some debug log spam when dragging a new connection to a node that can't take the link.
This moves the debug message back to its original place.
=> Fix minor debug log spam when dragging link

src/LGraphCanvas.ts, src/LGraphNode.ts, src/LiteGraphGlobal.ts
Snaps connecting links to the target slot when hovering over nodes.  An edge glow effect indicates that the link has snapped.
https://github.com/user-attachments/assets/f2f2f1da-71f9-4f44-93e5-d2230b5b72a8
- Uses existing hard-coded colours
- Snap border indicator can be disabled
- All features in this PR can be completely disabled via LiteGraph setting
- Does _not_ use animations
=> Snaps for Comfy 🫰

src/LGraphCanvas.ts, src/LiteGraphGlobal.ts, src/interfaces.ts, src/types/events.ts, src/utils/arrange.ts
Some minor changes in:
- [Fix circular depdency in global](https://github.com/Comfy-Org/litegraph.js/commit/5894e8eeb1f1a43b1547f1ffdeb0ea2298cd40fd)
- [Add TS type guard private function](https://github.com/Comfy-Org/litegraph.js/commit/c7f8589ce61e27cfa61495a2a464f57ff3d98d89)
- [Split node arrange code out to separate file](https://github.com/Comfy-Org/litegraph.js/commit/d369c33b1df5e3cea5848e3f5df56523cb59de05)
The rest is:
- Add / fix TS strict types
- Add property initializers
- Docs
=> Add / fix canvas TS strict types, doc

src/LGraph.ts, tsconfig.json
Bumps ECMAScript requirement to `ES2023`.  Can shim if this is an issue.
=> Fix group order unexpectedly reversing

vite.config.mts
Fixes broken relative imports generated by `vite-plugin-dts`.  e.g. in `dist/types/serialisation.d.ts`:
Old:
`import { LGraph } from '../../../../../../../src/LGraph';`
New:
`import { LGraph } from '../LGraph';`
=> Fix types not resolving through '@/imports' (.d.ts only)

src/LGraphCanvas.ts, src/LGraphNode.ts
- Moves node pos getter/setter to class decl, from dynamic add in ctor
- Resolves long-standing bug with `LGraphCanvas.onDrawForeground`
- Fixes bug where canvas version gets bumped for no reason
- Clears a couple of `@ts-expect-error`
=> Minor bug fixes & refactors

src/LGraphCanvas.ts, src/LGraphNode.ts, src/types/serialisation.ts, src/types/widgets.ts
Adds support for hiding widgets and flagging them as advanced
[firefox_KM9druzde6.webm](https://github.com/user-attachments/assets/04514866-dc2c-4625-a9d2-e3600950b36c)
In this example i've made 2 random widgets advanced:
```
app.graph.nodes.find(n => n.type === "EmptyLatentImage").widgets[1].advanced = true;
app.graph.nodes.find(n => n.type === "KSampler").widgets[1].advanced = true;
```
Scanned through all the references to `widgets` so hopefully didn't miss anywhere that was using them for size calculations.
=> Hidden & advanced widgets

src/LGraph.ts, src/LGraphCanvas.ts, src/LGraphNode.ts, src/LLink.ts, src/MapProxyHandler.ts, src/types/serialisation.ts
Graph `links` updated to use `Map`.  Public interface now supports both object and `Map`-style access via `Proxy`.
Direct access to the `Map` object is via `_links`, if the temporary Proxy is not suitable.
Adds new `asSerialisable` interface, allowing LLink to be migrated away from being an object serialiased as an array.  The current `serialize` method used throughout Litegraph is a bit counter-intuititve; it doesn't actually serialize anything.
=> Convert Links to ES6 Map & LLink Serialisation

test/LGraph.test.ts, test/LGraphNode.test.ts
- Adds some simple tests
- Replaces import of `../dist/*.js` with imports of the typescript source
The tests are written in typescript, and will fail to compile even basic tests due to only getting basic inference.
If it is preferred to test against `dist` (which is understandable), `js` tests for this could be added.
=> Add basic tests

src/LGraph.ts, src/LGraphCanvas.ts, src/LGraphGroup.ts, src/LGraphNode.ts, src/interfaces.ts, src/measure.ts, src/types/serialisation.ts
Allows user-positionable canvas objects (groups, nodes, future-types) to share common features such as selection, arranging, and movement.  Enables a more intuitive and natural UX.
- Node `size` is now a getter/setter backed by a `Rect`; array ref can no longer be overwritten (in line with `pos` and groups)
- Node `is_selected` is now a legacy accessor for `Positionable.selected`
- Adds `renderArea` - calculated once per frame, replacing repeat calls to getBounding (and onBounding callback)
- Adds `id` to groups
-----
- Removes unused margin checks from `get_X_OnPos` functions
- Some test failures are expected; there are minor differences in node resize
- The arbitrary +1 width added to nodes during render is still present on this branch
=> Positionable: Common interface for canvas items

src/LGraphCanvas.ts, src/LGraphGroup.ts, src/interfaces.ts, src/measure.ts
https://github.com/user-attachments/assets/f51adeb1-028e-40af-81e4-0ac13075198a
Nodes are now only considered "inside" a group when their centre point is inside the group:
https://github.com/user-attachments/assets/cc426082-0095-48ec-84c6-e47dfacfb187
Groups are only "inside" a group when wholly-contained by the parent group
https://github.com/user-attachments/assets/2abc0e17-00e6-41a4-a66e-72b8769ae27b
- Adds `selectedItems` - all currently selected `Positionable` canvas items
- Adds generic handlers for canvas items
- Temporary `selectedGroups` property cleaned up
Note: There are quirks with group movement and what constitutes group "membership".  These aren't new with this PR, but they are _improved_ by it, at least a little.
=> Add multi select & group nesting

src/LGraphCanvas.ts, src/LGraphGroup.ts
- Moves titlebar background render code from frontend to Litegraph (overall simplification)
- Fixes resize can go past bounds
- Moves hard-coded config to class static props
- Makes group resize area match the rendered area
Related: https://github.com/Comfy-Org/ComfyUI_frontend/pull/1418
=> Group update - titlebar, resize, config

src/LGraphNode.ts, test/LGraphNode.test.ts
Serialize node pos/size to plain js array to avoid change detection issue in the frontend. `Float32Array` behaves differently on `_.isEqual`.
=> Serialize to node pos/size to plain array

src/LGraphCanvas.ts
- Removes the arbitrary 5 graph unit margin in the node hitbox for pointer events and other tests
- Removes arbitrary +1 graph unit width to nodes (have not been able to find a reason for this - likely historic)
These can still be added, but the choice is now up to the consumer instead of being hard-coded into the lib.
=> Remove hard-coded modifications to nodes

src/LGraph.ts, src/LGraphNode.ts, src/LiteGraphGlobal.ts, src/litegraph.ts, src/types/serialisation.ts
- Adds module exports: `SerialisableGraph`, `SerialisableLLink`
- Adds new schema version - identified as `1`
- Adds `LGraph.asSerialisable` as preferred prep-for serialisation method
- Deprecates `LGraph.serialize`
- Has all the elements required to add reroutes
- Serialises `LLink` as object instead of array
- Ensures stale links are not kept when clearing graph
- Moves `last_link_id` & `last_node_id` to settings plain object `LGraph.state`
=> Graph serialisation update - Links & Reroutes

src/LGraphCanvas.ts
Resolves https://github.com/Comfy-Org/ComfyUI_frontend/issues/1489
This PR makes sure the up-to-date text size is used for node title and node subtext set in ComfyUI color palette.
=> Fix NODE_TEXT_SIZE style option

src/LGraph.ts, src/LGraphCanvas.ts, src/LGraphGroup.ts, src/LGraphNode.ts, src/LLink.ts, src/Reroute.ts, src/interfaces.ts, src/litegraph.ts, src/types/globalEnums.ts, src/types/serialisation.ts, src/utils/collections.ts
Native reroutes are added by this PR, along with the supporting framework.  Much of this work can be extended to implement new canvas types.
This PR gets the core infrastructure for reroutes in and testable, without touching ~~a thousand~~ two thousand lines of code.
More ways create & manage reroutes are planned.
- ⚠️ Reroutes are off by default
- Enable per-canvas by setting
```typescript
canvas.reroutesEnabled = true
```
https://github.com/user-attachments/assets/78403e3e-a79f-474f-bb70-cb5097d59664
https://github.com/user-attachments/assets/97520b7d-8756-4aa4-9e2e-e6c939eaa6a4
- No marker
- Default circles
- New directional Arrow
- Fixes centre link markers: now always centred for all link types (fixes dots rendered off to the side of straight vertical links, etc)
- Fixes crash if …
=> Add Reroutes

src/LGraph.ts, src/LGraphCanvas.ts, src/types/serialisation.ts
- Adds support for groups & reroutes
- Remaps links & reroutes, maintaining connections
- Fixes bug where pasted node links could be corrupted / lost by one bad node entry
https://github.com/user-attachments/assets/eff5d786-3399-41a3-95a3-52c9e5598882
- All items are run through `serialize` or `asSerialisable`
- All links to the inputs of copied nodes are included
- Nodes are still cloned as this behaviour is relied on in places, however original IDs are reinserted and copied
- Links use the new `Serialisable` interface, serialising them as objects like everything else
- Re-linking and ID mutation only occurs when pasting
- Paste returns map of original IDs to pasted items (`_paste` method only, at present - public API later if no issues)
This should provide a much cleaner way to extend …
=> Copy & Paste all items

README.md, src/CanvasPointer.ts, src/DragAndScale.ts, src/LGraph.ts, src/LGraphCanvas.ts, src/LGraphGroup.ts, src/LGraphNode.ts, src/LiteGraphGlobal.ts, src/interfaces.ts, src/litegraph.ts, src/measure.ts, src/types/events.ts, src/types/globalEnums.ts, test/__snapshots__/litegraph.test.ts.snap
This is a fundamental change to the way Litegraph handles pointer interaction.  Each pointer event is now tracked and managed by a `CanvasPointer`, created by the canvas as `LGraphCanvas.pointer`.
- Dragging multiple items no longer requires that the shift key be held down
- Clicking an item when multiple nodes / etc are selected will still deselect everything else
- Clicking a connected link on an input no longer disconnects and reconnects it
- Double-clicking requires that both clicks occur nearby
- Makes adding an option (later) to customise what modifier keys do actually feasible
- Intermittent issue where clicking a node slightly displaces it
- Alt-clicking to add a reroute creates two undo steps
For users, a lot of the change will be subtle, but it should "feel" more like a stable, …
=> Add CanvasPointer API

src/DragAndScale.ts
Replaces https://github.com/Comfy-Org/litegraph.js/pull/297
We can now observe the drag and scale change from vue side by creating a proxy on DragAndScaleState.
=> Add DragAndScaleState for external proxy

src/LGraphCanvas.ts
Resolves https://github.com/Comfy-Org/ComfyUI_frontend/issues/1611
Fixes a regression in fast widget conversion introduced in #308.  The fast widget conversion is only available for exactly one pointermove event.  Subsequent events clear it.  This explains how it passed tests.
=> Fix fast widget conversion

src/LGraphCanvas.ts, src/types/widgets.ts
Resolves https://github.com/Comfy-Org/ComfyUI_frontend/issues/1641
=> Fix custom widgets not receiving pointermove events

src/LGraphCanvas.ts
Resolves https://github.com/Comfy-Org/ComfyUI_frontend/issues/1627
Logic for onWidgetChanged callback refactored to work in CanvasPointer callbacks.
=> Fix custom nodes not responding to changed widget values

src/LGraphCanvas.ts
Resolves #338
`LGraphCanvas.node_widget` is set during `processMouseDown` - a legacy state variable that is set to the last widget that was clicked.  Cleared on pointerup.
Some custom widgets expect to handle all pointer events, whilst others expect to only receive pointerdown events.  The API was unclear, so guesswork appears to have been used.
Using node_widget, they should only receive movement events whilst dragging on the widget.
=> Fix custom widget mouseover

src/LGraphCanvas.ts
Problem / history:
- `widget.mouse()` return value controls canvas redraw
- Return value ignored due to Litegraph bug
- Return value not implemented by extension authors - there was no guidance and it did nothing (_not assigning blame_)
- Litegraph bug now fixed
- Nodes broken
Solution:
- If return value is nullish, ignore it
- If return value provided, use it to control canvas redraw
Additional:
- `pointermove` events are not fired outside of node bounds (no GH issues for this yet)
- Restores original behaviour by moving the widget callback out of conditional blocks
Resolves Comfy-Org/ComfyUI_frontend/issues/1641
=> Fix invalid callback return value preventing canvas redraw

src/LGraphCanvas.ts
Resolves #341
~~On a valid click, custom widgets using the `widget.mouse` callback will receive the `pointerup` event.~~
`pointerup` events are now sent to custom widgets in the same fashion as prior to #308.
A potential edge case break with this impl. is external mutation of `LGraphCanvas.node_widget` during a drag event.  Can be revisited if required, but I don't think this should be supported to begin with.
=> Fix widget.mouse callback does not receive pointerup events

src/LGraphCanvas.ts
Resolves Comfy-Org/ComfyUI_frontend/issues/1696
Changes the slider drag callback to use the current value from `pointermove` event rather than the the original `pointerdown` event, to set the slider value.
=> Fix slider regression caused by CanvasPointer

src/LGraphCanvas.ts
Extensions are using the LiteGraph double-click timer to perform their own calculations.
- Fixes a regression in that behaviour and ensures that the pointerup event sent to widgets via the `mouse()` callback has the click_time property set.
=> Ensure click_time is available to custom widgets

src/LGraphCanvas.ts
Fixes basic syntax error causing one of the widget.mouse calls to return `[NaN, NaN]` for pos.
The parameter is entirely redundant, as it is just a subtraction of fields in the other two paramters.  It is however, currently in use.
=> Fix custom widget pointerup receives NaN pos

src/LGraphNode.ts
=> Export types for frontend repo DTS

src/LGraphCanvas.ts
Adds an property to LGraphCanvas to specify maximum render frames per second.
Currently, the only limit to FPS is the refresh rate of the screen, reported by the browser.  Users with very high refresh rates experience unnecessarily high GPU usage.
Usage:
```ts
// Limit FPS to 30
canvas.maximumFps = 30
// Existing behaviour (Default):
canvas.maximumFps = 0
```
=> Add maximum FPS option to LGraphCanvas

src/DragAndScale.ts
Current behaviour impacts any canvas where canvas element top,left != client area 0,0
Zoom bad:
https://github.com/user-attachments/assets/7b82ba41-1d8f-4ec3-ae75-e103ff10bec6
Zoom good:
https://github.com/user-attachments/assets/25c7e598-20a7-4e8e-8238-d50d5db0d1ad
=> Fix canvas zoom centre not centred on pointer

src/LGraphBadge.ts, src/LGraphCanvas.ts, src/LGraphGroup.ts, src/LiteGraphGlobal.ts, test/__snapshots__/litegraph.test.ts.snap
- Uses node "type" as a fallback title
- Removes headache-inducing hard-coded error colour
```ts
LiteGraph.NODE_ERROR_COLOUR = "#d61"
```
```ts
LiteGraph.use_legacy_node_error_indicator = true
```
Continues to be highly visible on busy workflows, even fully zoomed out:
- Renames `drawSelectionBounding` => `strokeShape`
- Extends the API to include thickness & colour
- Fixes scaling of padding with rounded corners:
=> Redesign invalid node indicator

src/LGraphNode.ts
Pin node
right click -> clone -> crash
or copy/paste -> crash
=> Fix cloning pinned nodes

API.md, src/CanvasPointer.ts, src/LGraphCanvas.ts, src/types/widgets.ts
Adds `onPointerDown` callback to node widgets.  A few benefits of the new API:
- Simplified usage
- Exposes callbacks like "double click", removing the need to time / measure multiple pointer events
- Unified UX - same API as used in the rest of Litegraph
- Honours the user's click speed and pointer accuracy settings
```ts
// Callbacks for each pointer action can be configured ahead of time
widget.onPointerDown = function (pointer, node, canvas) {
const e = pointer.eDown
const offsetFromNode = [
e.canvasX - node.pos[0],
e.canvasY - node.pos[1],
]
// Click events - no overlap with drag events
pointer.onClick = (upEvent) => {
// Provides access to the whole lifecycle of events in every callback
console.log(pointer.eDown)
console.log(pointer.eMove ?? "Pointer didn't move") …
```
=> Add CanvasPointer callback for node widgets

src/litegraph.ts
`LiteGraphCanvasEventType` is unused in downstream so also remove it.
=> Export LGraphEventMode

src/LGraph.ts, src/LGraphCanvas.ts
This PR adds `LGraph.empty` shorthand to check whether the graph is empty.
=> Add LGraph.empty

src/LGraph.ts, src/LGraphCanvas.ts
- No change to internal functionality
- Replaces forced spread of all items on every property access with generator function
- Consumers that require an array can very cleanly spread into one
=> Optimise positionableItems / empty getters

src/LGraphCanvas.ts, src/LGraphNode.ts, src/draw.ts, src/interfaces.ts
This PR adds `INodeSlot.localized_name` to help us localize the UI while not persisting the localization.
=> [i18n] Add INodeSlot.localized_name field

src/LiteGraphGlobal.ts, src/litegraph.ts, test/__snapshots__/litegraph.test.ts.snap
Allows users to configure and utilise the Reroute class in the same manner as all other configurable classes.
=> Export Reroute class the same as other similar classes

src/LGraph.ts, src/Reroute.ts
Only part of the reroute is drawn at the selected scale.
`radius = 2`
Allows Reroute size to be changed via `radius` static property, per original design:
`radius = 2`
`radius = 7`
`radius = 20`
=> Fix reroutes ignore change in radius

src/LGraphCanvas.ts
Resolves https://github.com/Comfy-Org/ComfyUI_frontend/issues/1913
Display value even the widget label is present.
=> Fix slider value display when widget.label is present

src/LGraphCanvas.ts, src/litegraph.ts, src/types/events.ts
- Add `node-double-click` event to match the `group-double-click` event
- Remove unused interface `LiteGraphCanvasGroupEvent`
=> Emit node-double-click event

src/LGraphCanvas.ts
Return early from `drawConnections` after clearing `renderedPaths` when link visibility is toggled off, fixing #392 and #394 and hiding reroutes alongside links.
Add checks to prevent reroute entries in the context menu and ignore reroute clicks when link visibility is disabled.
Before / After:
https://github.com/user-attachments/assets/a7e6972f-aad9-43d1-b2d1-84a05b4f7a01
https://github.com/user-attachments/assets/55812173-8968-43e2-b984-c53f6c4ea312
=> Disable interaction with links and reroutes when visibility is off

src/LGraphCanvas.ts
In javascript `!![]` evals to `true`, so the old check would always pass if the callback obeys the type signature, which can cause an extra `null` item being added (separator). This PR fixes the issue which makes empty array return value generate a separator.
```typescript
getExtraMenuOptions?(
this: LGraphNode,
canvas: LGraphCanvas,
options: IContextMenuValue[],
): IContextMenuValue[]
```
=> Stricter return value check on LGraphCanvas.getExtraMenuOptions

src/ContextMenu.ts
- Resolves https://github.com/Comfy-Org/ComfyUI_frontend/issues/2059
Removes a line of broken legacy code.  This was detected during TS conversion, but the error was squashed to prevent unintentional downstream breakage. 
Issue report indicates it is always an error, and is safe to remove.
=> Fix deeply nested context menus remain open

src/LGraphCanvas.ts
Upstreams cursor style adjustment based from ComfyUI_frontend. Previous change in litegraph broke the vue side watcher logic.
Ref: https://github.com/Comfy-Org/ComfyUI_frontend/blob/52180243955ffcf3ce6e03a346ab2fb55aebe29b/src/components/graph/GraphCanvas.vue#L222-L236
=> Upstream grab cursor style

src/LGraphCanvas.ts
Update on dependency state change.
=> Properly update cursor style on mouse/keyboard events

src/LGraphCanvas.ts, src/types/events.ts
- Resolves #403
- Replaces #411
Problematic code was found and fixed by @catboxanon in #411.  This PR simply refactors it to use an existing call to `getBoundingRect`, where all the calculations were already being made (but discarded).
=> Add workaround for Firefox pointer events

public/css/litegraph.css, src/ContextMenu.ts, src/interfaces.ts
Replaces manual scroll logic in context menu with native browser scrolling via CSS properties.
This feature has been requested many times, for example:
- https://github.com/Comfy-Org/ComfyUI_frontend/issues/102
- https://github.com/comfyanonymous/ComfyUI/issues/6162
- https://github.com/comfyanonymous/ComfyUI/issues/4193
- https://github.com/comfyanonymous/ComfyUI/issues/144
According to code search, [this](https://github.com/OgreLemonSoup/ComfyUI-Load-Image-Gallery/blob/772819f29c5129836c287038735c542010246c02/js/LoadImageGallery.js) is the only instance of someone using `scroll_speed` and this change would not significantly affect that.
[invertMenuScrolling.ts](https://github.com/Comfy-Org/ComfyUI_frontend/blob/9c1eacf0afa359eeb6ab03dd7fbfc10e9fe46f3c/src/extensions/core/invertMenuScroll …
=> Use scrollbars in context menu

src/LGraphCanvas.ts
Fixes issue in which the canvas is left in a dragging state after using Pan Mode. `dragging_canvas` is set to false by the pointer cleanup but `_previously_dragging_canvas` is then `true` when the spacebar keyup occurs.
To reproduce issue:
1. Click (hold)
2. Space (hold)
3. Release click
4. Release space
5. Move mouse
=> Fix canvas stuck in dragging state after using Pan Mode 

src/types/widgets.ts
- Frontend decoupling PR (required for tests): https://github.com/Comfy-Org/ComfyUI_frontend/pull/2303
- Removes downstream types incorrectly added to litegraph
- Fix widget `computeSize` to match public usage
- Clean up
=> Fix TS types - Widgets

src/LGraphCanvas.ts, src/LGraphGroup.ts, src/LiteGraphGlobal.ts, src/draw.ts, src/litegraph.ts, test/__snapshots__/litegraph.test.ts.snap
This PR:
- Deprecates `LGraphCanvas.round_radius`.
- Adds `LiteGraph.ROUND_RADIUS`.
- Moves strokeShape from LGraphCanvas to draw.
=> [Refactor] Move strokeShape from LGraphCanvas to draw

src/draw.ts
Previously the function does not respect the dynamic change to LiteGraph global env, as the default are set when the function is defined.
=> Fix strokeShape default option values

src/LGraphNode.ts
`LiteGraph.NODE_COLLAPSED_HEIGHT` is undefined. Currently there is no dependency on LGraphNode.height so it should be safe to make the change.
=> Fix LGraphNode.height

src/LGraphCanvas.ts
`LGraphCanvas.render_title_colored` is always true according to code search. The value is not read anywhere as well. Removing the unnecessary flag.
=> Remove LGraphCanvas.render_title_colored

src/LGraphCanvas.ts, src/LGraphNode.ts
This PR moves node color fallback logic from LGraphCanvas to LGraphNode.
=> [Refactor] Move node color fallback from LGraphCanvas to LGraphNode

src/LGraphCanvas.ts
Ref: https://github.com/Comfy-Org/litegraph.js/pull/442
Replace a few other usages of direct zoom comparison.
=> Replace zoom scale check with low_quality flag check

src/LGraphNode.ts, src/LiteGraphGlobal.ts
Code search shows there is no current usage of the field. https://cs.comfy.org/search?q=context%3Aglobal+supported_extensions&patternType=keyword&case=yes&sm=0&df=%5B%22lang%22%2C%22JavaScript%22%2C%22lang%3Ajavascript%22%5D&__cc=1
We might also want to remove `LiteGraph.node_types_by_file_extension` later as follow-up.
=> Remove LGraphNode.supported_extensions

src/LiteGraphGlobal.ts
The same logic is repeated here in https://github.com/Comfy-Org/litegraph.js/blob/610ebd6ffecbbda3d8fe90e19f8850467f5e7d87/src/LGraphNode.ts#L300-L324.
Any `base_node` that inherits `LGraphNode` should automatically get the setter and getter defined.
=> Remove unnecessary getter/setter register on LGraphNode.shape

src/LGraphCanvas.ts, src/LGraphNode.ts
Reverts Comfy-Org/litegraph.js#452
Reason:
Fails playwright test
Expected:
Actual:
=> Revert "[Refactor] Move node title background draw logic to LGraphNode"

src/LGraphCanvas.ts, src/LGraphNode.ts, src/NodeSlot.ts
This PR implements the `NodeInputSlot` and `NodeOutputSlot` classes.
Codesearch shows that the only usage of direct push to LGraphNode.inputs/outputs is in rgthree. 
- Query: https://cs.comfy.org/search?q=context:global+inputs.push%28%7B&patternType=keyword&case=yes&sm=0&filters=%5B%5B%22lang%22%2C%22JavaScript%22%2C%22lang%3Ajavascript%22%5D%5D
- Callsite: https://cs.comfy.org/github.com/rgthree/rgthree-comfy/-/blob/web/comfyui/dynamic_context_base.js?L91
Maybe the conversion is not necessary?
=> Implement NodeSlot

src/DragAndScale.ts
Don't modify the input arg array.
Ref: https://github.com/Comfy-Org/litegraph.js/pull/487
=> Prevent modification on zooming_center arg in DragAndScale

src/LGraphNode.ts, test/LGraphNode.test.ts
Avoid frequent on-spot class creation from plain object.
=> Convert i/o slot to class in LGraphNode.configure

src/LGraphNode.ts, test/LGraphNode.test.ts
Reverts Comfy-Org/litegraph.js#511
Relands #506 
Reverted changes on `widgets_values` loop as it is hacked by custom nodes to be an object.
=> Revert "Revert "Convert i/o slot to class in LGraphNode.configure""

src/LGraphCanvas.ts, src/LGraphNode.ts, src/NodeSlot.ts, src/interfaces.ts, src/measure.ts, src/utils/layout.ts
Replaces https://github.com/Comfy-Org/litegraph.js/pull/510
This PR handles a smaller scope that only rewrites the layout/draw of node slots.
Layout objects are stored directly on original slot refs as `_layoutElement`.
=> Split layout and draw for slots

src/LGraphCanvas.ts
The function is unused according to https://cs.comfy.org/search?q=context:global+%22adjustNodesSize%22&patternType=keyword&sm=0&filters=%5B%5B%22lang%22%2C%22JavaScript%22%2C%22lang%3Ajavascript%22%5D%5D
=> [Cleanup] Remove LGraphCanvas.adjustNodesSize

src/LGraphCanvas.ts, src/LGraphNode.ts
https://github.com/Comfy-Org/litegraph.js/blob/de10bf0c3a2a187fc0cd55bd72e1718a0ae5976f/src/LGraphCanvas.ts#L4049-L4062
already calls `LGraphNode.measure` for every LGraphNode visible. This PR removes the unnecessary call to `measure` and directly reuse the result on `LGraphNode.boundingRect`.
This PR also removes the node size change during drawing. The collapsed width measuring is moved to `LGraphNode.measure`.
=> [Performance] Avoid double measure on node rendering

src/LGraphNode.ts, src/types/widgets.ts
Ref: https://github.com/Comfy-Org/ComfyUI_frontend/issues/2567
Reverse the priority of computeSize and computeLayoutSize. Allow custom nodes which overrides the `computeSize` of the widget to still take effect even on DOMWidget instance the `computeLayoutSize` is used.
=> Reverse computeSize and computeLayoutSize priority

src/LGraphCanvas.ts
LGraphGroup and reroute are also passed:
https://github.com/Comfy-Org/litegraph.js/blob/f010180b79ecab0b6f867ceaafc07e5b83b1fbe3/src/LGraphCanvas.ts#L3679-L3714
=> Type onSelectionChange

src/LGraphCanvas.ts
Properly clear LGraphCanvas.selectedItems when LGraphCanvas.clear is called.
=> Clear selectedItems on canvas clear

src/LGraphGroup.ts
The `LGraphGroup.color` can be deleted here. Marking it as optional. 
https://github.com/Comfy-Org/litegraph.js/blob/aafd7202c2db569113a355fd89a35ad685efcc2c/src/LGraphCanvas.ts#L1436-L1448
=> [Type] Mark LGraphGroup.color as optional

src/LGraphGroup.ts, src/LGraphNode.ts, src/interfaces.ts, src/litegraph.ts
Removes internal `#colorOption` as it does not work with serialization/configure.
=> Fix IColorable.getColorOption

src/LGraphCanvas.ts
Call `LGraphCanvas.deleteSelected` to properly sync various states on canvas, instead of calling lower level APIs on graph instance directly.
=> [BugFix] Call LGraphCanvas.deleteSelected on context menu remove

src/NodeSlot.ts, src/interfaces.ts, test/NodeSlot.test.ts
`pos` is dynamically calculated during layout. So it should not be persisted to workflow.
=> Remove NodeSlot.pos when serializing WidgetInputSlot

src/LGraph.ts, src/LGraphCanvas.ts, src/LGraphNode.ts
- Replaces traditional incrementing `for` loops and `forEach()` calls with modern `for..of` syntax
- Improves readability
- Changes are type checked, but all refactors in this PR required minor refactoring to satisfy strict type checking
- Issues were all related to dereferencing or the mutability of e.g. `.length`
- Expect no impact for single-thread browser code
- Low risk remains
=> [Refactor] Prefer modern for..of loops 2

src/types/widgets.ts, src/widgets/ButtonWidget.ts, src/widgets/TextWidget.ts
Remove `value` field from `ButtonWidget`. Move `clicked` property from `BaseWidget` to `ButtonWidget`.
=> Type ButtonWidget

src/LGraphNode.ts
- Guards against nullish `graph`
- [Fix regression in return type - getInputLink](https://github.com/Comfy-Org/litegraph.js/commit/143ca5f3f282d27474cd9a1ddf1b591a36a84cde) - long-standing, so no impact apparently
- Resolves some potential null dereferencing
=> [TS] Use strict mode in LGraphNode - part 2

src/LGraphCanvas.ts, src/LGraphNode.ts
This fixes an issue with widget heights not coinciding with actual computed heights.
=> Fix widget sizing logic in LGraphCanvas and LGraphNode

eslint.config.js, src/NodeSlot.ts, src/types/serialisation.ts, src/utils/object.ts, test/NodeSlot.test.ts
Serialize linked widget on node input slot properly according to current save format in https://github.com/Comfy-Org/ComfyUI_frontend/blob/76818b54e63e7332ca5a63b4ac129169f00208c7/src/extensions/core/widgetInputs.ts
=> Serialize NodeInputSlot.widget

src/types/widgets.ts, src/utils/widget.ts, src/widgets/KnobWidget.ts, src/widgets/NumberWidget.ts, test/utils/widget.test.ts
There are external code still dependent on the fact that Widget.options.step is scaled 10x, so the 10x-ed value is still kept there, while we use the new unscaled step2 within our code now.
Ref: https://cs.comfy.org/search?q=context:global+%22step+/+10%22&patternType=keyword&sm=0
=> Remove magic 10% scale on numeric widget step

.github/workflows/test-comfyui-frontend.yml
Sync https://github.com/Comfy-Org/ComfyUI_frontend/pull/2783
=> [CI] Update frontend install method

src/LGraphCanvas.ts
https://github.com/Comfy-Org/litegraph.js/pull/647 failed to convert `return` to `continue` when converting forEach to for-lop.
=> [BugFix] Fix add node via context menu (2)

src/LGraphNode.ts
Resolves https://github.com/Comfy-Org/litegraph.js/issues/739
This is a temporary measurement to fix the issue. We should probably consider build a more robust layout mechanism later.
=> [Bug] Fix node empty space on converted widget

src/NodeSlot.ts, src/utils/object.ts
Simplify the serialization code, so that we only write each prop once.
=> Implement _.pick to simplify serialization

src/LGraphNode.ts, src/types/widgets.ts
Currently widget needs to get access to `LGraphCanvas` instance to know whether the canvas is rendering in low quality (Zoomed out). Usually canvas object is obtained from `ComfyApp` instance.
This PR passes the lowQuality value to `IWidget.draw` to decouple the dependency on `LGraphCanvas`.
=> Add lowQuality param to IWidget.draw

src/LGraphCanvas.ts
Avoid trigger `onSelectionChange` when nothing is selected.
=> Early return in LGraphCanvas.deselectAll

src/LGraphCanvas.ts, src/LiteGraphGlobal.ts, test/__snapshots__/litegraph.test.ts.snap
The fallback option was added in https://github.com/Comfy-Org/litegraph.js/pull/358. So far no code is using this legacy fallback option. Removing it now.
=> [Cleanup] Remove use_legacy_node_error_indicator

src/LGraphCanvas.ts, src/LGraphNode.ts, src/draw.ts, test/__snapshots__/ConfigureGraph.test.ts.snap, test/__snapshots__/LGraph.test.ts.snap, test/__snapshots__/LGraph_constructor.test.ts.snap
This should allow frontend drop the stroke logic in hijack of `drawNodeShape`. Example usage:
```ts
node.strokeStyles["executionError"] = (this: LGraphNode) => 
app.lastNodeErrors?.[this.id] ? { colour: 'red', thickness: 2 } : undefined
```
=> Add LGraphNode.strokeStyles API

src/NodeSlot.ts, src/interfaces.ts
Upstream slot error rendering from ComfyUI_frontend.
=> Upstream render of slot error

src/NodeSlot.ts, src/interfaces.ts
INodeSlot.widget is not real widget references at runtime. This PR narrows the type so that we don't run into unexpected issues.
=> [TS] Properly type slot widget

test/LinkConnector.integration.test.ts
Disable `"Should move input links"` test case as it fails validation.
Ref: https://github.com/Comfy-Org/litegraph.js/issues/881
=> [Test] Validate slot links after each test

src/canvas/MovingInputLink.ts, test/LinkConnector.integration.test.ts
Ref: https://github.com/Comfy-Org/litegraph.js/issues/881
This PR fixes the corrupted link state when moving link from one input socket to another.
=> [Bug] Fix slot link state corruption on moving link between sockets

test/LinkConnector.integration.test.ts
Ref: https://github.com/Comfy-Org/litegraph.js/issues/881
Verifies that moving output links does not cause link corruption.
=> [Test] Add test on moving output links

src/LGraphCanvas.ts, src/LGraphNode.ts, src/NodeSlot.ts, src/types/widgets.ts, src/widgets/BaseWidget.ts, src/widgets/BooleanWidget.ts, src/widgets/ButtonWidget.ts, src/widgets/ComboWidget.ts, src/widgets/KnobWidget.ts, src/widgets/NumberWidget.ts, src/widgets/SliderWidget.ts, src/widgets/TextWidget.ts
This PR is the litegraph side change necessary for widget sockets feature in ComfyUI_frontend. Changes include
- Add readonly `Widget.computedDisabled` property for getting the computed disabled state. When the associated socket is connected, the widget is disabled
- Dynamically show the associated socket when
- the mouse is over the widget
- the slot is valid during link drop
- the slot is connected
- Removes the legacy widget drop behavior
Ref: https://github.com/Comfy-Org/rfcs/pull/9
=> Support associated socket for widgets

src/LGraphCanvas.ts, src/LGraphNode.ts
Moves layout of LGraphNode slot and widget to `LGraphNode.layout`. Codesearch shows that there is currently no usage on posY arg, so we can just pass null to it instead. https://cs.comfy.org/search?q=context:global+drawNodeWidgets&patternType=keyword&sm=0
=> [Refactor] Add LGraphNode.layout

src/LGraphNode.ts, test/LGraphNode.test.ts
Before:
After:
Workflow:
[dynamically_added_input.json](https://github.com/user-attachments/files/19640371/dynamically_added_input.json)
This PR also fixes the issue that output slot's `pos` property is not relative to node pos.
=> [Bug] Fix layout issue caused by absolute positioned slots

src/LGraphNode.ts, src/types/widgets.ts
https://github.com/Comfy-Org/ComfyUI_frontend/pull/3323
Some widgets are only used for display purpose (The preview image widget), their value shouldn't be serialized into the workflow. This PR adds a flag to allow widget to skip value serialization.
=> Add IBaseWidget.serialize flag

src/LiteGraphGlobal.ts
Currently, when node defs are refreshed (e.g., by pressing "r" shortcut), every single node def is logged, which is useless when there's hundred of nodes and clutters console. This PR changes to only log those messages when in debug mode.
=> Don't log every single node being replaced when node defs refreshed

src/LGraphNode.ts, test/LGraphNode.test.ts
Follow up on https://github.com/Comfy-Org/litegraph.js/pull/915
Filter out non-serializable widgets during node configuration. Current usage in frontend should not be affected as preview media widgets are mostly dynamically added at the end of widget list.
=> [Bug] Fix configure of non-serializable widget

src/LGraphNode.ts, src/NodeSlot.ts, src/interfaces.ts, src/utils/layout.ts
Resolves https://github.com/Comfy-Org/litegraph.js/issues/939
The prop is unused and is causing object clone circular ref issue.
=> [Bug] Remove unused prop LayoutElement.value

src/subgraph/SubgraphNode.ts
Fixes #1130
When loading workflows with promoted widgets, a TypeError occurs because `_listenerController` is not properly initialized on deserialized input slots.
- Add proper type checking before calling `abort()` on `_listenerController`
- Applied in 3 locations: `#addSubgraphInputListeners`, `configure`, and `onRemoved`
- Load a workflow with promoted DOM widgets
- Verify no TypeError occurs
- Verify event listeners are still properly cleaned up when needed
=> [fix] Handle missing _listenerController.abort when loading workflows

src/types/widgets.ts, src/widgets/BaseWidget.ts
The `parentSubgraphNode` property on widgets was typed as `LGraphNode`, which has private fields (`#concreteInputs`, `#concreteOutputs`). This caused TypeScript compilation failures in downstream projects when plain objects (without these private fields) were assigned to this property during deserialization.
This PR changes the type to `NodeLike` interface, which represents the shape of a node without requiring the private fields, allowing both actual `LGraphNode` instances and plain objects to be assigned without type errors.
=> [fix] Change parentSubgraphNode type to NodeLike

test/subgraph/SubgraphMemory.test.ts
Removes tests that appeared to be generated from an LLM hallucination, keeping only valid memory management tests. The removed tests included placeholder assertions like `expect(true).toBe(true)` and attempts to document memory leaks without actual GC capabilities.
Fixes #1132
=> [test] Clean up SubgraphMemory tests to remove invalid assertions

src/LGraphCanvas.ts, src/LiteGraphGlobal.ts, test/__snapshots__/litegraph.test.ts.snap
Feature required in ComfyUI Project V3 https://www.notion.so/drip-art/Standardize-Canvas-Navigation-2166d73d365080c9b84ad3f7b3b265bc?d=21f6d73d3650805eb3d2001ca7e88ed6#2176d73d3650802a9457dc2affe798e0
And it will be used in ComfyUI Frontend PR here.
it will have two mode: standard and legacy.
On standard mode (this is new), we will disable dragging canvas by mouse left click pan, and move canvas will be allowed by mouse middle button or spacebar+left-click
=> Add canvasNavigationMode for changing left click pan behaviour

src/subgraph/ExecutableNodeDTO.ts, src/subgraph/SubgraphNode.ts, test/subgraph/SubgraphMemory.test.ts, test/subgraph/SubgraphNode.test.ts
Enhanced RecursionError messages throughout the subgraph system to provide actionable debugging information when circular references are detected.
- Added node ID, title, subgraph name, and depth information
- Clear explanation that circular references create infinite loops in hierarchy
- Added node information with optional title
- Added path context showing subgraph nesting
- Added slot-specific details and unique ID for debugging
- Clear explanation about infinite loops in link resolution
=> [enhance] Add rich context to RecursionError messages

src/subgraph/SubgraphNode.ts
This PR fixes the link rendering issue when removing slots from subgraph IO nodes. Previously, when using the "Remove Slot" context menu option on SubgraphInputNode or SubgraphOutputNode, the slot names and colors would shift correctly but the connected links would remain at their old positions until a manual canvas update was triggered.
- Added `this.setDirtyCanvas(true, true)` calls in SubgraphNode's event handlers for `removing-input` and `removing-output` events
- This ensures the parent canvas (where the SubgraphNode and its links are rendered) gets updated when slots are removed from the IO nodes
We need both layers set dirty (`setDirtyCanvas(true, true)`) because:
1. The foreground needs updating because the node's slots visually shift
2. The background needs updating because the …
=> [fix] Update canvas when removing subgraph IO slots to re-render links

src/subgraph/SubgraphNode.ts, test/subgraph/SubgraphWidgetPromotion.test.ts
Fixes an issue where promoted widgets in subgraphs were losing their tooltip information during the promotion process.
When widgets are promoted from internal subgraph nodes to the subgraph's external interface, the tooltip property is now preserved through a getter that returns the original widget's tooltip value.
=> [fix] Preserve tooltips when promoting widgets to subgraph inputs

src/canvas/LinkConnector.ts, src/canvas/ToInputFromIoNodeLink.ts, src/infrastructure/LinkConnectorEventMap.ts, test/subgraph/SubgraphSlotConnections.test.ts, test/subgraph/SubgraphWidgetPromotion.test.ts
this PR adds a special check for SUBGRAPH_INPUT_ID because of incompatabilities with it being a virtual node.
maybe we can add a cleaner support for this later, but it does fix the issue for now.
https://github.com/user-attachments/assets/3c8a44e1-0b3f-4a93-90a6-08bb735a093f
fixes https://github.com/Comfy-Org/litegraph.js/issues/1170
also, #1182 might need to go in first, this branched off of that
=> Fix "Dragging from input slot connected to SubgraphInputNode creates new link instead of moving existing one"
