Comfy-Org/litegraph.js

package.json, src/litegraph.d.ts
This PR includes the type changes done during the TS migration of ComfyUI_frontend.
=> Make necessary type def changes for TS repo

package.json, src/litegraph.js
Use ESM style export instead of node style export.
=> Use ESM style export

src/litegraph.js
Requested in https://github.com/Comfy-Org/ComfyUI_frontend/pull/160
Adds deterministic serialization order.
=> Sort node on serialization

src/litegraph.js
From **Without Ordinary** on Discord:
> If a node is already pinned, change the text for "Pin" in the context menu to "Unpin"
=> Make node pin option text reactive

src/litegraph.js
Reverts Comfy-Org/litegraph.js#31
=> Revert "Add node disconnect shortcuts"

src/litegraph.js
Minor fix: someone forgot to finish their copy/paste, apparently.
=> Fix events not properly removed

src/litegraph.js
Improves UX by making wiring nodes easier.  The gap between slots is now gone.
https://github.com/user-attachments/assets/75010f04-668b-4459-a161-93a94be2f2e0
=> Increase node input & output slot hitboxes

src/litegraph.js
Reverts Comfy-Org/litegraph.js#68
Root reason:
https://github.com/Comfy-Org/ComfyUI_frontend/issues/381
=> Revert "LGraphNode ES6 class conversion"

src/litegraph.js
Reverts Comfy-Org/litegraph.js#72
=> Relands "LGraphNode ES6 class conversion"

src/litegraph.js
=> DragAndScale ES6 class conversion

src/litegraph.js
=> LGraphCanvas ES6 class conversion

src/litegraph.js
Fix error caused by merge.
Reapplies https://github.com/Comfy-Org/litegraph.js/pull/86
=> Fix prompt dialog dismiss

public/litegraph.d.ts, src/litegraph.js
Add `allow_searchbox` and `showSearchBox` to `LGraphCanvas.showConnectionMenu`'s options arg.
=> showConnectionMenu with searchbox options

src/litegraph.js
Moves draw logic from `LGraphCanvas` to `LGraphGroup`
=> Refactor LGraphGroup.draw

public/litegraph.d.ts, src/litegraph.js
Pinned group & node will not be movable / resizable.
=> Support group pinning and show pin icon on pinned node & group

src/litegraph.js
Fix regression caused by https://github.com/Comfy-Org/litegraph.js/pull/117
=> Fix group title detect

src/litegraph.js
Found a bug this when merging #114 into my TS - node param missed in refactor.  Converted it to an option instead.
=> Fix collapsed regression in #114

package-lock.json, package.json, public/litegraph.d.ts, src/LGraphBadge.ts, src/litegraph.js, vite.config.mts
Support rendering of multiple badges over `LGraphNode`.
=> Add `LGraphBadge` support on node

public/litegraph.d.ts
Adds export for ContextMenu (and clamp because why not)
=> Fix ContextMenu.root build / test fails

src/litegraph.js
=> Allow link creation from another link by shift+clicking

src/draw.ts
=> Restyle hollow circle node slot

src/litegraph.js
Adds events for begin/end change to allow changeTracker to group multiple changes into a single action
These are to replace the existing litegraph methods.
=> Add change events, to use instead of litegraph change methods.

src/litegraph.js
Adds compat for some extensions
=> Context menu ES6 class conversion

src/litegraph.js
Nothing special - just converted
=> CurveEditor ES6 class conversion

src/LGraphCanvas.ts, src/LiteGraphGlobal.ts
https://github.com/user-attachments/assets/a8a882fe-3066-494a-8737-5c1793e01ba8
Related issue: https://github.com/Comfy-Org/ComfyUI_frontend/issues/1011
=> Change cursor shape to grab on dragging

src/LGraphGroup.ts, src/LiteGraphGlobal.ts, src/litegraph.js, src/polyfills.ts
Based on #170
- Splits polyfills out to separate file
- Moves LiteGraph.LGraphClass definitions over to the global class definition
- Moves LGraphGroup prototype extensions to class decl
=> Clean litegraph module entry file

src/LGraphCanvas.ts
Press space enters read-only panning mode. The cursor style change will be handled by Vue side.
=> Canvas panning mode

public/litegraph.d.ts, src/LiteGraphGlobal.ts
Adds hidden link enum value for `LGraphCanvas.links_render_mode`.
=> Add hidden link enum

src/LGraph.ts, src/types/serialisation.ts
- All functional changes (except some null checks) should be in `Refactor TS narrowing & coercion` commit
- Only TS type-narrowing changes are made
- Cleans & simplifies code
- Clears `ts-nocheck`
=> Typescript LGraph

src/LLink.ts
Adds TS types and color getter/setter to LLink
=> Typescript LLink

src/LGraph.ts, src/LGraphNode.ts, src/litegraph.ts, src/types/serialisation.ts
Converts LGraphNode to TypeScript and resolves most issues.
Commits are mostly split up by type of change, hopefully making review easier.
Important commits:
- [Refactor LGraphNode.findSlotByType](https://github.com/Comfy-Org/litegraph.js/commit/a0a7e1a7e6e20cb07f04e0341d6506acd472cfbe)
Other commits with output changes:
- [Convert special-case vars](https://github.com/Comfy-Org/litegraph.js/commit/0ba8ece6fd43a52d42fe087039be4d47c3da16df)
- [Refactor - minor logic change](https://github.com/Comfy-Org/litegraph.js/commit/c811130c53e4ce89f41b95aafc9d4ea1b2e632b2)
- [Add TS types - overloads w/workaround](https://github.com/Comfy-Org/litegraph.js/commit/c029206ee11afdd8fa51b326a6ef628fdc4ff91d)
- [Refactor - prefer typeof over constructor …
=> Typescript LGraphNode

src/ContextMenu.ts, src/interfaces.ts
Commits with actual changes:
- [Refactor TS narrowing & coercion](https://github.com/Comfy-Org/litegraph.js/commit/231ac562d6c581db2045aa3d6f415c9f1fc4425e)
- [Refactor optional chaining](https://github.com/Comfy-Org/litegraph.js/commit/ee2056145462221b5f87cb3f1bd511749f6ad811)
- [Add TS narrowing](https://github.com/Comfy-Org/litegraph.js/commit/3deb248780d821bf789bafce9bcf08cd6deff245)
- [Refactor - TS type narrowing](https://github.com/Comfy-Org/litegraph.js/commit/da418744814f52323382ded08d28471d5998b167)
- [Convert to arrow funcs for this ref](https://github.com/Comfy-Org/litegraph.js/pull/206/commits/2358de960ade4a80997094bfe7dadba891d1121f)
=> Typescript ContextMenu

src/DragAndScale.ts
- TS types added
- Mostly just marking things deprecated
- Two optional chaining calls added
[Refactor - optional chaining](https://github.com/Comfy-Org/litegraph.js/commit/968aacd76488ad1da7152ffaca6b6540b03cfd8f)
=> Typescript DragAndScale

src/CurveEditor.ts
TS conversion of CurveEditor - didn't bother to split this one out.
=> Convert CurveEditor to TypeScript

src/LGraphNode.ts, src/LiteGraphGlobal.ts, src/types/globalEnums.ts, src/types/serialisation.ts
Pretty sure the only real changes are these two:
- [Refactor - prefer typeof over constructor check](https://github.com/Comfy-Org/litegraph.js/commit/29cc4156d5ebabbbf54c0c0bfdd0d614f8a1d03e)
- [Refactor - optional chaining](https://github.com/Comfy-Org/litegraph.js/commit/9692863abc5f15a5027341c57f87f4b83ace7e51)
=> Typescript LiteGraphGlobal

src/LGraphCanvas.ts, src/LiteGraphGlobal.ts, src/litegraph.ts
Replaces some circular logic with more obvious initialisation.
=> Fix circular dependency

src/LGraphNode.ts
=> Fix node shape change ignored

src/LGraphCanvas.ts, src/LGraphGroup.ts
=> Fix group deselected on title click

src/LGraph.ts, src/LGraphCanvas.ts, src/LGraphGroup.ts, src/LGraphNode.ts, src/LLink.ts, src/LiteGraphGlobal.ts, src/measure.ts, src/polyfills.ts, src/types/events.ts, src/types/serialisation.ts
- Replaces LiteGraph.CONST usage with enums
- Just a bunch of nits
=> Code clean up

package.json, scripts/release.js
Add a release script to help create release PR. Run `npm run release` to create a release PR.
=> Add release script

src/LGraph.ts, src/LGraphNode.ts, src/interfaces.ts, src/measure.ts, src/types/serialisation.ts
- Adds exported measure functions for code re-use
- Adds TS types
=> Shared measure functions

.github/workflows/test-comfyui-frontend.yml
Follow-up on https://github.com/Comfy-Org/ComfyUI_frontend/pull/1400
=> Update test ci action

.prettierrc, package.json, public/css/litegraph.css, src/ContextMenu.ts, src/CurveEditor.ts, src/DragAndScale.ts, src/LGraph.ts, src/LGraphBadge.ts, src/LGraphCanvas.ts, src/LGraphGroup.ts, src/LGraphNode.ts, src/LLink.ts, src/LiteGraphGlobal.ts, src/MapProxyHandler.ts, src/draw.ts, src/interfaces.ts, src/litegraph.ts, src/measure.ts, src/polyfills.ts, src/strings.ts, src/types/events.ts, src/types/globalEnums.ts, src/types/serialisation.ts, src/types/widgets.ts, src/utils/arrange.ts, test/LGraph.test.ts, test/LGraphNode.test.ts
This PR reverts the master branch to cb6e80a64571f2d4ff2e9fb19c81f88f6473186c, pre format.
Reason: https://github.com/Comfy-Org/litegraph.js/pull/198
Branch protection rule is updated to disallow direct commit to master.
=> Revert branch to cb6e80a64571f2d4ff2e9fb19c81f88f6473186c

src/LGraphCanvas.ts, src/litegraph.ts, src/types/globalEnums.ts
Relands 9b0f572ca1bdfe74f15046f3d784df0abd096ae1
Changes:
- Make `EaseFunction` a global enum
- Convert optional positional args to kwargs
=> Reland animateToNode

src/LGraphCanvas.ts
- Renames `deleteSelectedItems` to `deleteSelected` (to match naming of existing functions)
- Minor refactor to preserve my sanity when locally rebasing
=> Update delete selected

src/LGraph.ts, src/LGraphCanvas.ts, src/LGraphNode.ts, src/LLink.ts, src/types/events.ts, src/types/serialisation.ts, src/types/widgets.ts, src/utils/arrange.ts
All minor refactors / nits.
Minor changes:
- [Add minor code change to support stricter types](https://github.com/Comfy-Org/litegraph.js/commit/1d3a1f3f230116784e928b7e4f9ddb8648712ce4)
- [Optimise - remove 2d context save/restore](https://github.com/Comfy-Org/litegraph.js/commit/8f6b2d8b58184d49e0ee77bd43e189ced7511854)
- Simplify downstream typing: [Remove string LLink IDs](https://github.com/Comfy-Org/litegraph.js/commit/c03c8140961d40fe3eba478b91ea3c22fcb323e9)
No runtime changes:
- Add TS types
- Remove commented code blocks
- Docs
=> Code cleanup, docs, TS types

src/LGraphCanvas.ts, src/LGraphNode.ts, src/interfaces.ts
=> Fix pin not respected by multi-select move

src/LGraphCanvas.ts, src/LGraphGroup.ts, src/litegraph.ts, src/measure.ts
Follow-up of https://github.com/Comfy-Org/litegraph.js/pull/282.
Move createBounds to measure.ts as it is not tied to LGraphGroup.
=> Move createBounds to measure.ts

src/LGraphCanvas.ts
Select, delete, undo.
https://github.com/user-attachments/assets/8a554e71-5a50-4943-bcbe-e591cb22e50b
=> Emit only one change when deleting nodes

src/LGraph.ts, src/LGraphCanvas.ts
Reverts Comfy-Org/litegraph.js#297
Reason: Needs better mechanism to detect widget value changes and node changes.
=> Revert "Add canvas update events"

src/LGraphCanvas.ts, src/utils/collections.ts
=> Fix pinned group contents moving

src/LGraphCanvas.ts
Resolves https://github.com/Comfy-Org/ComfyUI_frontend/issues/1603
=> Fix widget not updating on combo click

src/LGraphCanvas.ts
=> Use device scaling for drag-from-link checks

src/LGraphCanvas.ts
=> Prevent distortion of area select rectangle

src/LGraphCanvas.ts
- Resolves #395
Edit: Additional - this issue also occurs after shift-clicking a link line (drag new link from link).
=> Fix thick selection rectangle after adding reroute

src/ContextMenu.ts
Requires that fonts scale in increments of 0.25.
=> Fix scaled font blurriness in context menus

src/LGraphCanvas.ts
Follow-up on https://github.com/Comfy-Org/litegraph.js/pull/407
Tracks correct dragging state.
=> Track LGraphState.draggingCanvas

src/LGraphCanvas.ts
=> Fix #421 - selection box is always a square

lint-staged.config.js, package-lock.json, package.json, src/CanvasPointer.ts, src/ContextMenu.ts, src/CurveEditor.ts, src/DragAndScale.ts, src/LGraph.ts, src/LGraphCanvas.ts, src/LGraphGroup.ts, src/LGraphNode.ts, src/LLink.ts, src/LiteGraphGlobal.ts, src/Reroute.ts, src/measure.ts, src/polyfills.ts, tsconfig.json
Adds https://github.com/allegro/typescript-strict-plugin to gradually migrate to ts-strict.
Sync https://github.com/Comfy-Org/ComfyUI_frontend/pull/1235
=> Add ts-strict-ignore plugin

src/LiteGraphGlobal.ts
Removes unused code.  Not in use by any code available on codesearch.
https://cs.comfy.org/search?q=wrapFunctionAsNode&patternType=keyword&sm=0
=> Remove unused code - wrapFunctionAsNode

src/LGraphCanvas.ts
=> Remove unused LGraphCanvas.onMenuNodeToSubgraph

public/css/litegraph.css
Ref: https://github.com/Comfy-Org/litegraph.js/pull/458/files#r1940503699
=> Add back accidental removed css rule

src/LGraphCanvas.ts, src/LGraphNode.ts
Relands https://github.com/Comfy-Org/litegraph.js/pull/452
Fixes collapsed node title size issue.
=> [Reland][Refactor] Move node title background draw logic to LGraphNode 

.github/workflows/test-comfyui-frontend.yml
Speed up tests. Chromium2x issues will be detected when litegraph is updated in the main frontend repo.
=> [Test] Disable Chromium2x tests

src/LGraphCanvas.ts
Currently there is no dependency on the `isConnectUnselected` outside ComfyUI core code. Changing the signature should be fine.
Ref: https://cs.comfy.org/search?q=pasteFromClipboard&patternType=keyword&sm=0
=> Support override of paste position on LGraphCanvas.pasteFromClipboard

src/LGraphCanvas.ts
Ref:
https://github.com/Comfy-Org/ComfyUI_frontend/blob/dda9a72966fc58542474189a15b9601deecc210e/src/scripts/app.ts#L493-L535
=> Upstream drag zoom feature from ComfyUI_frontend

src/LGraphCanvas.ts, src/LGraphNode.ts, src/types/widgets.ts, src/utils/type.ts, src/widgets/BaseWidget.ts, src/widgets/BooleanWidget.ts
Extract boolean widget drawing logic to a separate class.
Test ref: https://github.com/Comfy-Org/ComfyUI_frontend/pull/2421
=> Implement BooleanWidget

src/LGraphCanvas.ts, src/LGraphNode.ts, src/types/widgets.ts, src/widgets/SliderWidget.ts
Also support the onClick adjust slider value feature.
=> Implement SliderWidget

src/LGraphCanvas.ts
Reverts Comfy-Org/litegraph.js#473
Breaks zoom drag. Ref: https://github.com/Comfy-Org/ComfyUI_frontend/issues/2468
=> Revert "[Refactor] Update style"

src/LGraphCanvas.ts
Relands https://github.com/Comfy-Org/litegraph.js/pull/473
The issue on DragAndScale has been fixed in https://github.com/Comfy-Org/litegraph.js/pull/489
=> Reland "[Refactor] Update style"

src/LGraphNode.ts, test/LGraphNode.test.ts
Reverts Comfy-Org/litegraph.js#506
Reason:
https://github.com/Comfy-Org/ComfyUI_frontend/issues/2488
=> Revert "Convert i/o slot to class in LGraphNode.configure"

src/types/serialisation.ts
Ref: https://github.com/Comfy-Org/litegraph.js/pull/511
=> Add ISerialisedNode.widgets_values documentation

src/LGraphCanvas.ts, src/widgets/BaseWidget.ts, src/widgets/NumberWidget.ts, src/widgets/SliderWidget.ts
Trigger IWdiget.callabck on value update for `NumberWidget` and `SliderWidget`.
=> [BugFix] Trigger IWidget.callback on widget drag

src/LGraphCanvas.ts, src/LGraphNode.ts, src/NodeSlot.ts
=> Show widget input inplace

src/LGraphNode.ts
Ref: https://github.com/Comfy-Org/ComfyUI_frontend/issues/2624
=> [BugFix] Fix unknown node with converted widgets

src/LGraphNode.ts
Resolves https://github.com/Comfy-Org/ComfyUI_frontend/issues/2652
Resolves https://github.com/Comfy-Org/ComfyUI_frontend/issues/2651
Initial regression caused by https://github.com/Comfy-Org/litegraph.js/pull/531
=> [BugFix] Auto grow node if widgets need more space

src/interfaces.ts, src/litegraph.ts, src/typeGuards.ts
Ref: https://github.com/Comfy-Org/litegraph.js/pull/551#discussion_r1966839717
=> [nit] Move isColorable out of interfaces.ts

src/litegraph.ts
Export RenderShape, TitleMode enums.
=> Export enum

src/LGraphNode.ts
Reverts Comfy-Org/litegraph.js#601
Reason: breaks legacy reroute
On inserting a workflow with legacy reroute node
```
Uncaught (in promise) NullGraphError: Attempted to access LGraph reference that was null or undefined.
at RerouteNode.removeOutput (LGraphNode.ts:1425:28)
at RerouteNode.clone (rerouteNode.ts:215:18)
at LGraphCanvas.copyToClipboard (LGraphCanvas.ts:3331:29)
at Object.insertWorkflow (workflowService.ts:350:12)
```
=> Revert "[TS] Use strict mode in LGraphNode - part 2"

src/LGraphNode.ts
Reverts Comfy-Org/litegraph.js#603
=> [Reland][TS] Use strict mode in LGraphNode - part 2

src/interfaces.ts
Ref: https://github.com/Comfy-Org/ComfyUI_frontend/pull/2728
=> Move widget prop to INodeInputSlot

.github/workflows/test-comfyui-frontend.yml
Sync https://github.com/Comfy-Org/ComfyUI_frontend/pull/2733
=> Update devtools ref

src/LGraphCanvas.ts
Resolves https://github.com/Comfy-Org/ComfyUI_frontend/issues/2814
Culprit: https://github.com/Comfy-Org/litegraph.js/pull/647
=> [BugFix] Fix adding node via context menu

.github/workflows/test-comfyui-frontend.yml
Sync https://github.com/Comfy-Org/ComfyUI_frontend/pull/2775
=> [CI] Sync workflow_tempaltes fetch

src/LGraphCanvas.ts
Add LGraphCanvas.isNodeVisible or more efficient node visibility checks.
=> Add LGraphCanvas.isNodeVisible

src/LGraphCanvas.ts
Resolves https://github.com/Comfy-Org/ComfyUI_frontend/issues/2905
=> [Bug] Fix link drop on multi-line string dom widget

src/types/widgets.ts
Remove the prop as it is a impl detail of the frontend.
=> [TS] Remove IBaseWidget.element prop

src/LGraphNode.ts
Ref: https://github.com/Comfy-Org/litegraph.js/issues/616
Resolves https://github.com/Comfy-Org/litegraph.js/issues/770
This PR adds null-checks to various part of layout code to avoid we get into irrecoverable state.
=> [TS] Add null-checks for LGraphNode layouts

src/widgets/BaseWidget.ts, src/widgets/NumberWidget.ts
Resolves https://github.com/Comfy-Org/ComfyUI_frontend/issues/3204
=> [Bug] Fix number widget range not enforced

src/canvas/ToOutputRenderLink.ts, test/ToOutputRenderLink.test.ts
Resolves https://github.com/Comfy-Org/litegraph.js/issues/858
=> [Bug] Fix drag link from input to output

src/canvas/LinkConnector.ts
Resolves https://github.com/Comfy-Org/litegraph.js/issues/857
=> [Bug] Fix link drop on widget

src/LGraphNode.ts
Resolves https://github.com/Comfy-Org/litegraph.js/issues/925
https://github.com/user-attachments/assets/81bd6ce3-6feb-456a-9bb3-e512008b2e63
=> [Bug] Show widget slot when slot is hovered

.github/workflows/test-comfyui-frontend.yml
See https://github.com/Comfy-Org/ComfyUI_frontend/pull/3500 for details.
=> Remove fetch-templates script invoke in CI

src/DragAndScale.ts
Add DragAndScale.fitToBounds for use case that don't need animation.
=> Add DragAndScale.fitToBounds

src/subgraph/Subgraph.ts, test/subgraph/Subgraph.test.ts, test/subgraph/SubgraphNode.test.ts, test/subgraph/fixtures/README.md, test/subgraph/fixtures/subgraphFixtures.ts, test/subgraph/fixtures/subgraphHelpers.ts, test/subgraph/fixtures/testSubgraphs.json
- Created foundational test utilities that all subgraph developers will use
- Added Vitest fixtures for reusable test scenarios
- Implemented 30+ tests covering Subgraph construction, I/O management, events, and serialization
=> [feat] Add subgraph test infrastructure
